export const mainRoute = {
  home: {
    dashboard: '/',
  },
  app: {
    todo: '/',
  },
  game: {
    sudoku: '/',
    ticTacToe: '/',
  },
  uiComponent: {
    screen: {
      breakpoint: '/',
      display: '/',
      box: '/',
      position: '/',
      overflow: '/',
    },
    flexboxAndGrid: {
      flex: '/',
      grid: '/',
      gap: '/',
      justify: '/',
      align: '/',
      place: '/',
    },
    typography: '/',
    action: {
      button: '/',
      buttonGroup: '/',
      dropdown: '/',
      modal: '/',
      swap: '/',
    },
    dataDisplay: {
      alert: '/',
      avatar: '/',
      badge: '/',
      card: '/',
      carousel: '/',
      chatBubble: '/',
      collapse: '/',
      countdown: '/',
      kbd: '/',
      progress: '/',
      radialProgress: '/',
      stat: '/',
      tooltip: '/',
    },
    input: {
      calendar: '/',
      checkbox: '/',
      fileInput: '/',
      dateTimeInput: '/',
      radioButton: '/',
      range: '/',
      rating: '/',
      select: '/',
      switch: '/',
      textInput: '/',
      inputGroup: '/',
    },
    table: '/',
    layout: {
      divider: '/',
      drawer: '/',
      footer: '/',
      hero: '/',
      indicator: '/',
      mask: '/',
      stack: '/',
      toast: '/',
    },
    navigation: {
      breadcrumb: '/',
      bottomNavigation: '/',
      link: '/',
      menu: '/',
      navbar: '/',
      pagination: '/',
      steps: '/',
      tab: '/',
    },
    mockup: {
      code: '/',
      phone: '/',
      window: '/',
    },
    icon: {
      a: '/',
      b: '/',
      c: '/',
    },
  },
}

export const authRoute = {
  login: '/',
  register: '/',
  forgotPassword: '/',
  resetPassword: '/',
}

export const errorRoute = {
  400: '/',
  401: '/',
  403: '/',
  404: '/',
  500: '/',
  503: '/',
  504: '/',
}
