export type ThemeMode = 'light' | 'dark'
export type ThemeDirection = 'ltr' | 'rtl'
export type ThemeNavMode = 'transparent' | 'themed'
export type ThemeLayout =
  | 'classic'
  | 'modern'
  | 'stack-side'
  | 'simple'
  | 'decked'
  | 'blank'
