/* eslint-disable @typescript-eslint/padding-line-between-statements */
import type { ScreenStyle } from './screen'
import type { NumericRange } from 'types'

export type GridColAmount = NumericRange<1, 12> | 'auto'
export type GridRowAmount = NumericRange<1, 6> | 'auto'
export type GridGapAmount = NumericRange<0, 12> | 0

export type GridColSpanAmount = NumericRange<1, 12>
export type GridColStartAmount = NumericRange<1, 13>

export type GridRowSpanAmount = NumericRange<1, 6>
export type GridRowStartAmount = NumericRange<1, 7>

// * Please note that the grid is not supported in IE11
/** Because this file too long,
 * * You can use shortcut `ctrl + k, ctrl + j` to fold the code
 * * And can use `ctrl + k, ctrl + 0` to unfold the code
 */
// Note: Please understand the tailwind why we are using this way to define the className

export const GRID_COL: ScreenStyle<GridColAmount> = {
  default: {
    auto: 'grid-flow-col',
    1: 'grid-cols-1',
    2: 'grid-cols-2',
    3: 'grid-cols-3',
    4: 'grid-cols-4',
    5: 'grid-cols-5',
    6: 'grid-cols-6',
    7: 'grid-cols-7',
    8: 'grid-cols-8',
    9: 'grid-cols-9',
    10: 'grid-cols-10',
    11: 'grid-cols-11',
    12: 'grid-cols-12',
  },
  xs: {
    auto: 'xs:grid-flow-col',
    1: 'xs:grid-cols-1',
    2: 'xs:grid-cols-2',
    3: 'xs:grid-cols-3',
    4: 'xs:grid-cols-4',
    5: 'xs:grid-cols-5',
    6: 'xs:grid-cols-6',
    7: 'xs:grid-cols-7',
    8: 'xs:grid-cols-8',
    9: 'xs:grid-cols-9',
    10: 'xs:grid-cols-10',
    11: 'xs:grid-cols-11',
    12: 'xs:grid-cols-12',
  },
  sm: {
    auto: 'sm:grid-flow-col',
    1: 'sm:grid-cols-1',
    2: 'sm:grid-cols-2',
    3: 'sm:grid-cols-3',
    4: 'sm:grid-cols-4',
    5: 'sm:grid-cols-5',
    6: 'sm:grid-cols-6',
    7: 'sm:grid-cols-7',
    8: 'sm:grid-cols-8',
    9: 'sm:grid-cols-9',
    10: 'sm:grid-cols-10',
    11: 'sm:grid-cols-11',
    12: 'sm:grid-cols-12',
  },
  md: {
    auto: 'md:grid-flow-col',
    1: 'md:grid-cols-1',
    2: 'md:grid-cols-2',
    3: 'md:grid-cols-3',
    4: 'md:grid-cols-4',
    5: 'md:grid-cols-5',
    6: 'md:grid-cols-6',
    7: 'md:grid-cols-7',
    8: 'md:grid-cols-8',
    9: 'md:grid-cols-9',
    10: 'md:grid-cols-10',
    11: 'md:grid-cols-11',
    12: 'md:grid-cols-12',
  },
  lg: {
    auto: 'lg:grid-flow-col',
    1: 'lg:grid-cols-1',
    2: 'lg:grid-cols-2',
    3: 'lg:grid-cols-3',
    4: 'lg:grid-cols-4',
    5: 'lg:grid-cols-5',
    6: 'lg:grid-cols-6',
    7: 'lg:grid-cols-7',
    8: 'lg:grid-cols-8',
    9: 'lg:grid-cols-9',
    10: 'lg:grid-cols-10',
    11: 'lg:grid-cols-11',
    12: 'lg:grid-cols-12',
  },
  xl: {
    auto: 'xl:grid-flow-col',
    1: 'xl:grid-cols-1',
    2: 'xl:grid-cols-2',
    3: 'xl:grid-cols-3',
    4: 'xl:grid-cols-4',
    5: 'xl:grid-cols-5',
    6: 'xl:grid-cols-6',
    7: 'xl:grid-cols-7',
    8: 'xl:grid-cols-8',
    9: 'xl:grid-cols-9',
    10: 'xl:grid-cols-10',
    11: 'xl:grid-cols-11',
    12: 'xl:grid-cols-12',
  },
} as const

export const GRID_ROW: ScreenStyle<GridRowAmount> = {
  default: {
    auto: 'grid-flow-row',
    1: 'grid-rows-1',
    2: 'grid-rows-2',
    3: 'grid-rows-3',
    4: 'grid-rows-4',
    5: 'grid-rows-5',
    6: 'grid-rows-6',
  },
  xs: {
    auto: 'xs:grid-flow-row',
    1: 'xs:grid-rows-1',
    2: 'xs:grid-rows-2',
    3: 'xs:grid-rows-3',
    4: 'xs:grid-rows-4',
    5: 'xs:grid-rows-5',
    6: 'xs:grid-rows-6',
  },
  sm: {
    auto: 'sm:grid-flow-row',
    1: 'sm:grid-rows-1',
    2: 'sm:grid-rows-2',
    3: 'sm:grid-rows-3',
    4: 'sm:grid-rows-4',
    5: 'sm:grid-rows-5',
    6: 'sm:grid-rows-6',
  },
  md: {
    auto: 'md:grid-flow-row',
    1: 'md:grid-rows-1',
    2: 'md:grid-rows-2',
    3: 'md:grid-rows-3',
    4: 'md:grid-rows-4',
    5: 'md:grid-rows-5',
    6: 'md:grid-rows-6',
  },
  lg: {
    auto: 'lg:grid-flow-row',
    1: 'lg:grid-rows-1',
    2: 'lg:grid-rows-2',
    3: 'lg:grid-rows-3',
    4: 'lg:grid-rows-4',
    5: 'lg:grid-rows-5',
    6: 'lg:grid-rows-6',
  },
  xl: {
    auto: 'xl:grid-flow-row',
    1: 'xl:grid-rows-1',
    2: 'xl:grid-rows-2',
    3: 'xl:grid-rows-3',
    4: 'xl:grid-rows-4',
    5: 'xl:grid-rows-5',
    6: 'xl:grid-rows-6',
  },
} as const

export const GRID_GAP: ScreenStyle<GridGapAmount> = {
  default: {
    0: 'gap-0',
    1: 'gap-1',
    2: 'gap-2',
    3: 'gap-3',
    4: 'gap-4',
    5: 'gap-5',
    6: 'gap-6',
    7: 'gap-7',
    8: 'gap-8',
    9: 'gap-9',
    10: 'gap-10',
    11: 'gap-11',
    12: 'gap-12',
  },
  xs: {
    0: 'xs:gap-0',
    1: 'xs:gap-1',
    2: 'xs:gap-2',
    3: 'xs:gap-3',
    4: 'xs:gap-4',
    5: 'xs:gap-5',
    6: 'xs:gap-6',
    7: 'xs:gap-7',
    8: 'xs:gap-8',
    9: 'xs:gap-9',
    10: 'xs:gap-10',
    11: 'xs:gap-11',
    12: 'xs:gap-12',
  },
  sm: {
    0: 'sm:gap-0',
    1: 'sm:gap-1',
    2: 'sm:gap-2',
    3: 'sm:gap-3',
    4: 'sm:gap-4',
    5: 'sm:gap-5',
    6: 'sm:gap-6',
    7: 'sm:gap-7',
    8: 'sm:gap-8',
    9: 'sm:gap-9',
    10: 'sm:gap-10',
    11: 'sm:gap-11',
    12: 'sm:gap-12',
  },
  md: {
    0: 'md:gap-0',
    1: 'md:gap-1',
    2: 'md:gap-2',
    3: 'md:gap-3',
    4: 'md:gap-4',
    5: 'md:gap-5',
    6: 'md:gap-6',
    7: 'md:gap-7',
    8: 'md:gap-8',
    9: 'md:gap-9',
    10: 'md:gap-10',
    11: 'md:gap-11',
    12: 'md:gap-12',
  },
  lg: {
    0: 'lg:gap-0',
    1: 'lg:gap-1',
    2: 'lg:gap-2',
    3: 'lg:gap-3',
    4: 'lg:gap-4',
    5: 'lg:gap-5',
    6: 'lg:gap-6',
    7: 'lg:gap-7',
    8: 'lg:gap-8',
    9: 'lg:gap-9',
    10: 'lg:gap-10',
    11: 'lg:gap-11',
    12: 'lg:gap-12',
  },
  xl: {
    0: 'xl:gap-0',
    1: 'xl:gap-1',
    2: 'xl:gap-2',
    3: 'xl:gap-3',
    4: 'xl:gap-4',
    5: 'xl:gap-5',
    6: 'xl:gap-6',
    7: 'xl:gap-7',
    8: 'xl:gap-8',
    9: 'xl:gap-9',
    10: 'xl:gap-10',
    11: 'xl:gap-11',
    12: 'xl:gap-12',
  },
} as const

export const GRID_COL_SPAN: ScreenStyle<GridColSpanAmount> = {
  default: {
    1: 'col-span-1',
    2: 'col-span-2',
    3: 'col-span-3',
    4: 'col-span-4',
    5: 'col-span-5',
    6: 'col-span-6',
    7: 'col-span-7',
    8: 'col-span-8',
    9: 'col-span-9',
    10: 'col-span-10',
    11: 'col-span-11',
    12: 'col-span-12',
  },
  xs: {
    1: 'xs:col-span-1',
    2: 'xs:col-span-2',
    3: 'xs:col-span-3',
    4: 'xs:col-span-4',
    5: 'xs:col-span-5',
    6: 'xs:col-span-6',
    7: 'xs:col-span-7',
    8: 'xs:col-span-8',
    9: 'xs:col-span-9',
    10: 'xs:col-span-10',
    11: 'xs:col-span-11',
    12: 'xs:col-span-12',
  },
  sm: {
    1: 'sm:col-span-1',
    2: 'sm:col-span-2',
    3: 'sm:col-span-3',
    4: 'sm:col-span-4',
    5: 'sm:col-span-5',
    6: 'sm:col-span-6',
    7: 'sm:col-span-7',
    8: 'sm:col-span-8',
    9: 'sm:col-span-9',
    10: 'sm:col-span-10',
    11: 'sm:col-span-11',
    12: 'sm:col-span-12',
  },
  md: {
    1: 'md:col-span-1',
    2: 'md:col-span-2',
    3: 'md:col-span-3',
    4: 'md:col-span-4',
    5: 'md:col-span-5',
    6: 'md:col-span-6',
    7: 'md:col-span-7',
    8: 'md:col-span-8',
    9: 'md:col-span-9',
    10: 'md:col-span-10',
    11: 'md:col-span-11',
    12: 'md:col-span-12',
  },
  lg: {
    1: 'lg:col-span-1',
    2: 'lg:col-span-2',
    3: 'lg:col-span-3',
    4: 'lg:col-span-4',
    5: 'lg:col-span-5',
    6: 'lg:col-span-6',
    7: 'lg:col-span-7',
    8: 'lg:col-span-8',
    9: 'lg:col-span-9',
    10: 'lg:col-span-10',
    11: 'lg:col-span-11',
    12: 'lg:col-span-12',
  },
  xl: {
    1: 'xl:col-span-1',
    2: 'xl:col-span-2',
    3: 'xl:col-span-3',
    4: 'xl:col-span-4',
    5: 'xl:col-span-5',
    6: 'xl:col-span-6',
    7: 'xl:col-span-7',
    8: 'xl:col-span-8',
    9: 'xl:col-span-9',
    10: 'xl:col-span-10',
    11: 'xl:col-span-11',
    12: 'xl:col-span-12',
  },
} as const

export const GRID_COL_START: ScreenStyle<GridColStartAmount> = {
  default: {
    1: 'col-start-1',
    2: 'col-start-2',
    3: 'col-start-3',
    4: 'col-start-4',
    5: 'col-start-5',
    6: 'col-start-6',
    7: 'col-start-7',
    8: 'col-start-8',
    9: 'col-start-9',
    10: 'col-start-10',
    11: 'col-start-11',
    12: 'col-start-12',
    13: 'col-start-13',
  },
  xs: {
    1: 'xs:col-start-1',
    2: 'xs:col-start-2',
    3: 'xs:col-start-3',
    4: 'xs:col-start-4',
    5: 'xs:col-start-5',
    6: 'xs:col-start-6',
    7: 'xs:col-start-7',
    8: 'xs:col-start-8',
    9: 'xs:col-start-9',
    10: 'xs:col-start-10',
    11: 'xs:col-start-11',
    12: 'xs:col-start-12',
    13: 'xs:col-start-13',
  },
  sm: {
    1: 'sm:col-start-1',
    2: 'sm:col-start-2',
    3: 'sm:col-start-3',
    4: 'sm:col-start-4',
    5: 'sm:col-start-5',
    6: 'sm:col-start-6',
    7: 'sm:col-start-7',
    8: 'sm:col-start-8',
    9: 'sm:col-start-9',
    10: 'sm:col-start-10',
    11: 'sm:col-start-11',
    12: 'sm:col-start-12',
    13: 'sm:col-start-13',
  },
  md: {
    1: 'md:col-start-1',
    2: 'md:col-start-2',
    3: 'md:col-start-3',
    4: 'md:col-start-4',
    5: 'md:col-start-5',
    6: 'md:col-start-6',
    7: 'md:col-start-7',
    8: 'md:col-start-8',
    9: 'md:col-start-9',
    10: 'md:col-start-10',
    11: 'md:col-start-11',
    12: 'md:col-start-12',
    13: 'md:col-start-13',
  },
  lg: {
    1: 'lg:col-start-1',
    2: 'lg:col-start-2',
    3: 'lg:col-start-3',
    4: 'lg:col-start-4',
    5: 'lg:col-start-5',
    6: 'lg:col-start-6',
    7: 'lg:col-start-7',
    8: 'lg:col-start-8',
    9: 'lg:col-start-9',
    10: 'lg:col-start-10',
    11: 'lg:col-start-11',
    12: 'lg:col-start-12',
    13: 'lg:col-start-13',
  },
  xl: {
    1: 'xl:col-start-1',
    2: 'xl:col-start-2',
    3: 'xl:col-start-3',
    4: 'xl:col-start-4',
    5: 'xl:col-start-5',
    6: 'xl:col-start-6',
    7: 'xl:col-start-7',
    8: 'xl:col-start-8',
    9: 'xl:col-start-9',
    10: 'xl:col-start-10',
    11: 'xl:col-start-11',
    12: 'xl:col-start-12',
    13: 'xl:col-start-13',
  },
} as const

export const GRID_COL_END: ScreenStyle<GridColStartAmount> = {
  default: {
    1: 'col-end-1',
    2: 'col-end-2',
    3: 'col-end-3',
    4: 'col-end-4',
    5: 'col-end-5',
    6: 'col-end-6',
    7: 'col-end-7',
    8: 'col-end-8',
    9: 'col-end-9',
    10: 'col-end-10',
    11: 'col-end-11',
    12: 'col-end-12',
    13: 'col-end-13',
  },
  xs: {
    1: 'xs:col-end-1',
    2: 'xs:col-end-2',
    3: 'xs:col-end-3',
    4: 'xs:col-end-4',
    5: 'xs:col-end-5',
    6: 'xs:col-end-6',
    7: 'xs:col-end-7',
    8: 'xs:col-end-8',
    9: 'xs:col-end-9',
    10: 'xs:col-end-10',
    11: 'xs:col-end-11',
    12: 'xs:col-end-12',
    13: 'xs:col-end-13',
  },
  sm: {
    1: 'sm:col-end-1',
    2: 'sm:col-end-2',
    3: 'sm:col-end-3',
    4: 'sm:col-end-4',
    5: 'sm:col-end-5',
    6: 'sm:col-end-6',
    7: 'sm:col-end-7',
    8: 'sm:col-end-8',
    9: 'sm:col-end-9',
    10: 'sm:col-end-10',
    11: 'sm:col-end-11',
    12: 'sm:col-end-12',
    13: 'sm:col-end-13',
  },
  md: {
    1: 'md:col-end-1',
    2: 'md:col-end-2',
    3: 'md:col-end-3',
    4: 'md:col-end-4',
    5: 'md:col-end-5',
    6: 'md:col-end-6',
    7: 'md:col-end-7',
    8: 'md:col-end-8',
    9: 'md:col-end-9',
    10: 'md:col-end-10',
    11: 'md:col-end-11',
    12: 'md:col-end-12',
    13: 'md:col-end-13',
  },
  lg: {
    1: 'lg:col-end-1',
    2: 'lg:col-end-2',
    3: 'lg:col-end-3',
    4: 'lg:col-end-4',
    5: 'lg:col-end-5',
    6: 'lg:col-end-6',
    7: 'lg:col-end-7',
    8: 'lg:col-end-8',
    9: 'lg:col-end-9',
    10: 'lg:col-end-10',
    11: 'lg:col-end-11',
    12: 'lg:col-end-12',
    13: 'lg:col-end-13',
  },
  xl: {
    1: 'xl:col-end-1',
    2: 'xl:col-end-2',
    3: 'xl:col-end-3',
    4: 'xl:col-end-4',
    5: 'xl:col-end-5',
    6: 'xl:col-end-6',
    7: 'xl:col-end-7',
    8: 'xl:col-end-8',
    9: 'xl:col-end-9',
    10: 'xl:col-end-10',
    11: 'xl:col-end-11',
    12: 'xl:col-end-12',
    13: 'xl:col-end-13',
  },
} as const

export const GRID_ROW_SPAN: ScreenStyle<GridRowSpanAmount> = {
  default: {
    1: 'row-span-1',
    2: 'row-span-2',
    3: 'row-span-3',
    4: 'row-span-4',
    5: 'row-span-5',
    6: 'row-span-6',
  },
  xs: {
    1: 'xs:row-span-1',
    2: 'xs:row-span-2',
    3: 'xs:row-span-3',
    4: 'xs:row-span-4',
    5: 'xs:row-span-5',
    6: 'xs:row-span-6',
  },
  sm: {
    1: 'sm:row-span-1',
    2: 'sm:row-span-2',
    3: 'sm:row-span-3',
    4: 'sm:row-span-4',
    5: 'sm:row-span-5',
    6: 'sm:row-span-6',
  },
  md: {
    1: 'md:row-span-1',
    2: 'md:row-span-2',
    3: 'md:row-span-3',
    4: 'md:row-span-4',
    5: 'md:row-span-5',
    6: 'md:row-span-6',
  },
  lg: {
    1: 'lg:row-span-1',
    2: 'lg:row-span-2',
    3: 'lg:row-span-3',
    4: 'lg:row-span-4',
    5: 'lg:row-span-5',
    6: 'lg:row-span-6',
  },
  xl: {
    1: 'xl:row-span-1',
    2: 'xl:row-span-2',
    3: 'xl:row-span-3',
    4: 'xl:row-span-4',
    5: 'xl:row-span-5',
    6: 'xl:row-span-6',
  },
} as const

export const GRID_ROW_START: ScreenStyle<GridRowStartAmount> = {
  default: {
    1: 'row-start-1',
    2: 'row-start-2',
    3: 'row-start-3',
    4: 'row-start-4',
    5: 'row-start-5',
    6: 'row-start-6',
    7: 'row-start-7',
  },
  xs: {
    1: 'xs:row-start-1',
    2: 'xs:row-start-2',
    3: 'xs:row-start-3',
    4: 'xs:row-start-4',
    5: 'xs:row-start-5',
    6: 'xs:row-start-6',
    7: 'xs:row-start-7',
  },
  sm: {
    1: 'sm:row-start-1',
    2: 'sm:row-start-2',
    3: 'sm:row-start-3',
    4: 'sm:row-start-4',
    5: 'sm:row-start-5',
    6: 'sm:row-start-6',
    7: 'sm:row-start-7',
  },
  md: {
    1: 'md:row-start-1',
    2: 'md:row-start-2',
    3: 'md:row-start-3',
    4: 'md:row-start-4',
    5: 'md:row-start-5',
    6: 'md:row-start-6',
    7: 'md:row-start-7',
  },
  lg: {
    1: 'lg:row-start-1',
    2: 'lg:row-start-2',
    3: 'lg:row-start-3',
    4: 'lg:row-start-4',
    5: 'lg:row-start-5',
    6: 'lg:row-start-6',
    7: 'lg:row-start-7',
  },
  xl: {
    1: 'xl:row-start-1',
    2: 'xl:row-start-2',
    3: 'xl:row-start-3',
    4: 'xl:row-start-4',
    5: 'xl:row-start-5',
    6: 'xl:row-start-6',
    7: 'xl:row-start-7',
  },
} as const

export const GRID_ROW_END: ScreenStyle<GridRowStartAmount> = {
  default: {
    1: 'row-end-1',
    2: 'row-end-2',
    3: 'row-end-3',
    4: 'row-end-4',
    5: 'row-end-5',
    6: 'row-end-6',
    7: 'row-end-7',
  },
  xs: {
    1: 'xs:row-end-1',
    2: 'xs:row-end-2',
    3: 'xs:row-end-3',
    4: 'xs:row-end-4',
    5: 'xs:row-end-5',
    6: 'xs:row-end-6',
    7: 'xs:row-end-7',
  },
  sm: {
    1: 'sm:row-end-1',
    2: 'sm:row-end-2',
    3: 'sm:row-end-3',
    4: 'sm:row-end-4',
    5: 'sm:row-end-5',
    6: 'sm:row-end-6',
    7: 'sm:row-end-7',
  },
  md: {
    1: 'md:row-end-1',
    2: 'md:row-end-2',
    3: 'md:row-end-3',
    4: 'md:row-end-4',
    5: 'md:row-end-5',
    6: 'md:row-end-6',
    7: 'md:row-end-7',
  },
  lg: {
    1: 'lg:row-end-1',
    2: 'lg:row-end-2',
    3: 'lg:row-end-3',
    4: 'lg:row-end-4',
    5: 'lg:row-end-5',
    6: 'lg:row-end-6',
    7: 'lg:row-end-7',
  },
  xl: {
    1: 'xl:row-end-1',
    2: 'xl:row-end-2',
    3: 'xl:row-end-3',
    4: 'xl:row-end-4',
    5: 'xl:row-end-5',
    6: 'xl:row-end-6',
    7: 'xl:row-end-7',
  },
} as const
